POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "memberId": "1",
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###
GET http://localhost:8000/member/passenger/query-list?page=2&size=1
Accept: application/json
token: {{token}}

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1858787944601620480,
  "memberId": 1858099215452999680,
  "name": "zj3",
  "idCard": "11111111111111111",
  "type": "1",
  "createTime": "2024-11-20 23:10:08"
}

###


